//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeTiger.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeTiger.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty.{0}Parameter name: {1}.
        /// </summary>
        internal static string ArgumentCannotBeEmptyMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmptyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot consist only of whitespace characters.{0}Parameter name: {1}.
        /// </summary>
        internal static string ArgumentCannotBeOnlyWhitespaceMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentCannotBeOnlyWhitespaceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be null.{0}Parameter name: {1}.
        /// </summary>
        internal static string ArgumentMustBeNullMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentMustBeNullMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be null or empty.{0}Parameter name: {1}.
        /// </summary>
        internal static string ArgumentMustBeNullOrEmptyMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentMustBeNullOrEmptyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be null or white space.{0}Parameter name: {1}.
        /// </summary>
        internal static string ArgumentMustBeNullOrWhiteSpaceMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentMustBeNullOrWhiteSpaceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not fall within the expected range..
        /// </summary>
        internal static string ArgumentOutOfRangeMessage {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lock is not currently acquired, so it cannot be released..
        /// </summary>
        internal static string LockNotAcquiredSoCannotBeReleasedMessage {
            get {
                return ResourceManager.GetString("LockNotAcquiredSoCannotBeReleasedMessage", resourceCulture);
            }
        }
    }
}
